apiVersion: v1
kind: Pod
metadata:
  name: californiaapp
  labels:
     app: california
spec:
  containers:
  - name: californiaapp
    image: subaniprasad/californiaapp:1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: california
  name: californiaapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: california
  type: LoadBalancer
status:
  loadBalancer: {}
